### ISSUE TITLE
URL constructor does not accept objects. The browsers that implement the spec do.

### ISSUE THREAD

**Issue by llimos** [lifaon74/url-polyfill#12]
If passing an object to the URL constructor, in Firefox and Chrome it will use the toString() property of the object as the URL to process. This is most obvious (and useful) when passing a Location object such as window.location.
The polyfill does not do this; it simply checks if the parameter is typeof string, and if not it throws an exception.

Line 173 of url-polyfill.js should be either removed or accept objects and call their toString() method.
Before the line
`if(typeof url !== 'string') throw new TypeError('Failed to construct \'URL\': Invalid URL');`
we can add
`if (typeof url === 'object') url = url.toString();`
which will solve the problem

**Comment by lifaon74** [comment]
I made the changes. But take care, the URL polyfill is not an attempt to be 100% in concordance with the specs else all type checks, special char escape, etc... would result in a huge file size. The URL class expects a string as input you should not pass something else even if the browser correct it ;)
