### ISSUE TITLE
URLSearchParams divergence from Firefox & Chrome

### ISSUE THREAD

**Issue by llienher** [lifaon74/url-polyfill#15]
Seems the URLSearchParams implentation is not consistent with the Firefox and Chrome behavior.

Using Chrome 63 and Firefox 57:
```
let url = new URL('https://www.example.com/?key=hello+world');
url.searchParams.get('key');
```

The result is: `"hello world"`

Using the polyfill and the same code in Edge 16, the result is:
`"hello+world"`

**Comment by lifaon74** [comment]
For full implementation please follow this: https://github.com/lifaon74/url-polyfill/issues/16
