### ISSUE TITLE
`pathname` using the mailto scheme defers to native URL

### ISSUE THREAD

**Issue by frenic** [lifaon74/url-polyfill#17]
In Chrome `pathname` of a mailto URL outputs the e-mail address.

```js
console.log(new URL('mailto:some.name@somehost.com').pathname);
// -> "some.name@somehost.com"
```

But using the `url-polyfill` it's prefixed with `/`.

```js
console.log(new URL('mailto:some.name@somehost.com').pathname);
// -> "/some.name@somehost.com"
```

**Comment by lifaon74** [comment]
As specified in the readme, the polyfill is not indented for all cases (to keep it light), but for the most generic. The full implementation is available here: https://github.com/lifaon74/url-polyfill/files/1572997/url.zip
