### ISSUE TITLE
Does not work in React Native (non-DOM scope)

### ISSUE THREAD

**Issue by Noitidart** [lifaon74/url-polyfill#18]
I am trying to use this in a react native project. When I do:

```
import 'url-polyfill'

console.log('URL:', URL);
console.log('url:', new URL('http://www.google.com?inq=true&q=1#inh=true&h=1'));
```

It errors with:

> document is not defined

Is it possible to use this in a non-DOM scope?

**Comment by lifaon74** [comment]
I don't known exactly what technologies are under the wood of react native. Could you try : https://github.com/lifaon74/url-polyfill/issues/16 where I provide a full implementation ?

**Comment by Noitidart** [comment]
Yep that fixes it for sure. As long as it doesn't depend on document. React Native is similar to node environment. thanks! should i close this out? it might be a standing issue for others.

**Comment by lifaon74** [comment]
I'll close it. Happy to help you.
