### ISSUE TITLE
Different behavior in IE and Chrome

### ISSUE THREAD

**Issue by KovDimaY** [lifaon74/url-polyfill#22]
I used this url-polyfill to validate the URL provided by the user and while testing in IE I realized that the behavior in IE and Google Chrom is completely different.

The function where I am using the url-polyfill is this:
![image](https://user-images.githubusercontent.com/26466644/37471880-0e95b448-286b-11e8-98b5-bbeaa607d866.png)

The logs in Chrome is this (which is correct behavior for "sdfdsfdsf" provided as a URL):
![image](https://user-images.githubusercontent.com/26466644/37462222-78883494-2851-11e8-9746-37bf5b6ab15c.png)

The logs in IE is this (which is not expected for the "sdfdsfdsf" provided as a URL):
![image](https://user-images.githubusercontent.com/26466644/37462277-ad161ba4-2851-11e8-86c9-730649c8861d.png)

Version of IE: 11.0.9600.18860
Version of Chrome: 64.0.3282.186
Environment: VM - Windows 7 (32)

**Comment by lifaon74** [comment]
As specified in the README, the polyfill is not 100% accurate. A full implementation will be several hundred of killobytes...
You could simply test if `url === new URL(url).href`

**Comment by KovDimaY** [comment]
Well, true...
Thank you for the advice! :D

**Comment by KovDimaY** [comment]
As a small comment about the `url === new URL(url).href` solution.

It does not work in general case, because `URL(url).href`always come with a "/" in the end. That means that if the user provides `https://www.google.com` as a `url`, the `URL(url).href = https://www.google.com/` and the condition becomes to be false. 

I used `Math.abs(url.length - URL(url).href.length) < 2` as a condition and it worked for all the cases I needed to cover. Maybe it will help you too.

**PS:** If you know a better solution or you see a flow in my current one, let me know, please. Thank you in advance! :D
