### ISSUE TITLE
Polyfill for server

### ISSUE THREAD

**Issue by frenic** [lifaon74/url-polyfill#24]
I used the `url.js` to polyfill `URL` and `URLSearchParams` on the server since it didn't use `document`. But that file is moved to `do-not-use/url.js` now. `url-polyfill.js` uses `document` in the constructor and basically just acts as a API on top of an DOM `<a>` so that doesn't work. Why shouldn't we use `url.js`?

**Comment by lifaon74** [comment]
You can find the full implementation for nodejs here : https://github.com/lifaon74/whatwg-url
Or upgrade to node > 8

**Comment by frenic** [comment]
Ah, ok. Thanks
