### ISSUE TITLE
searchParams should be two way bound

### ISSUE THREAD

**Issue by sirian** [lifaon74/url-polyfill#27]
1. URLSearchParams MUST be reused (like in #9)
2. modification of url.search MUST modify searchParams

Example:
```
const u = new URL('http://example.org/?')
const sp = u.searchParams
console.log(sp === u.searchParams);

u.search = "x=1"
console.log(sp.get('x'))


sp.set('y', 1)

console.log(u.search)
sp.set('y', null);
console.log('' + sp)
```

Look at screenshot (left - native URL, right - polyfill)

![image](https://user-images.githubusercontent.com/897643/41811647-32efff1a-771c-11e8-8421-ec16594e04df.png)

**Comment by sirian** [comment]
Another problem

```
s = new URLSearchParams('?&=y=&');

for (const entry of s) {
    console.log(JSON.stringify(entry))
}

console.log('' + s);
```

left - chrome, right - polyfill

![image](https://user-images.githubusercontent.com/897643/41811748-14ff1b92-771e-11e8-8ebb-b07867f3df92.png)

**Comment by lifaon74** [comment]
Fixed in https://github.com/lifaon74/url-polyfill/commit/53ddfbaccb8ff3e9eeb2cb57f48678cb43c291db

The special cases like `new URLSearchParams('?&=y=&')`can't be all polyfilled or the lib size would explode.
