### ISSUE TITLE
Empty URL properties when using base-URL

### ISSUE THREAD

**Issue by letorbi** [lifaon74/url-polyfill#3]
The `baseURL`-parameter passed to the constructor seems to be ignored when calculating the property values (e.g. `origin`) of the resulting URL object.

**Two screenshots from the IE11 console to illustrate the problem**

The first one shows the correct result, when creating an URL object without using a base-URL:

![ie11 url - without baseurl](https://cloud.githubusercontent.com/assets/1268015/25289284/3aec9196-26c9-11e7-83b4-f16dc2f48246.png)

The second shows the empty properties when the same URL is created of from a base-URL:

![ie11 url - with baseurl](https://cloud.githubusercontent.com/assets/1268015/25289322/659d92b4-26c9-11e7-83f5-91174a5ccfb8.png)

**Comment by lifaon74** [comment]
Ok fixed. Thanks for you bug reporting.
