### ISSUE TITLE
Crashes if document is not present

### ISSUE THREAD

**Issue by alexyuly** [lifaon74/url-polyfill#34]
This line of code causes a crash if `document` is not available:

https://github.com/lifaon74/url-polyfill/blob/master/url-polyfill.js#L262

This makes the package not usable in non-browser contexts, namely React Native.

**Comment by lifaon74** [comment]
Yes, legit behavior, the polyfill requires a document. The full implementation can be found here: https://github.com/lifaon74/whatwg-url

**Comment by lifaon74** [comment]
The polyfill tries to be the lighter as possible. For this it uses the HTMLAnchorElement from the DOM (so document is required)

**Comment by alexyuly** [comment]
Ok, thanks.
