### ISSUE TITLE
Constructor should throw when no base is given for relative URLs

### ISSUE THREAD

**Issue by caillou** [lifaon74/url-polyfill#37]
The following code should throw an `Invalid URL` error:

```javascript
new URL('/foo')
```

As of now, in both IE11 and Safari, `window.location.href` is assumed as `base`.

**Comment by janicklas-ralph** [comment]
This is a very good point since this behavior is non-standard. By default the URL class throws an error. So older browsers that end up using the polyfill will sometimes show incorrect result instead of throwing an error
