### ISSUE TITLE
Creating `new URLSearchParams()` throws error in ie11

### ISSUE THREAD

**Issue by oatkiller** [lifaon74/url-polyfill#38]
Here's a page i made in glitch (w/ some weird CDN stuff) that shows the issue. AFAIK, based on MDN, the initializer is optional. Here's what i was reading: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams

https://tan-brazil.glitch.me/

**Comment by lifaon74** [comment]
Hi, thanks for the report. v1.1.3 should fix it. Could you test please ?

**Comment by oatkiller** [comment]
@lifaon74 Thanks! works great. udabes
