### ISSUE TITLE
Error parsing invalid URL

### ISSUE THREAD

**Issue by myadzel** [lifaon74/url-polyfill#42]
Parsing `http:/localhost/` with the native URL returns

```js
{
  hash: "",
  host: "localhost",
  hostname: "localhost",
  href: "http://localhost/",
  origin: "http://localhost",
  password: "",
  pathname: "/",
  port: "",
  protocol: "http:",
  search: "",
  searchParams: {},
  username: ""
}
```

polyfill returns

```js
{
  hash: "",
  host: "",
  hostname: "",
  href: "http://localhost/localhost/",
  origin: "http://",
  password: "",
  pathname: "/localhost/",
  port: "",
  protocol: "http:",
  search: "",
  searchParams: {},
  username: ""
}
```

**Comment by lifaon74** [comment]
The polyfill should not be used to check url errors. It's light and because of it, it can't check every patterns. For a full implementation but bigger: https://github.com/lifaon74/whatwg-url

**Comment by myadzel** [comment]
>The polyfill should not be used to check url errors

It is expected that the URL polyfill will behave in the same way as the native URL.

**Comment by lifaon74** [comment]
Not possible: the full implementation is probably near the megabyte ! This is because of the support of punycodes, parser, unicode chars, etc... such a big polyfill is not recommended for user with limited bandwidth. Instead this polyfill covers 95%~99% of the specs which doesn't require long code.

As long as the url is correct, the parser will work as expected BUT in case of special url (unicode chars, malformed, etc..) the polyfill may be incorrect: Because of this, the polyfill SHOULD NOT be used to check if an url is fully correct or not (because there will always be a case where an url (provided by the client) is not compliant. So its unsafe !). For this, use on backend the whatwg-url instead.

**Comment by myadzel** [comment]
> Not possible: the full implementation is probably near the megabyte ! This is because of the support of punycodes, parser, unicode chars, etc... such a big polyfill is not recommended for user with limited bandwidth. Instead this polyfill covers 95%~99% of the specs which doesn't require long code.
> 
> As long as the url is correct, the parser will work as expected BUT in case of special url (unicode chars, malformed, etc..) the polyfill may be incorrect: Because of this, the polyfill SHOULD NOT be used to check if an url is fully correct or not (because there will always be a case where an url (provided by the client) is not compliant. So its unsafe !). For this, use on backend the whatwg-url instead.

**Comment by myadzel** [comment]
Thanks.

**Comment by zloirock** [comment]
@lifaon74 the main problem only in support custom encoding in search query params and malformed unicode character. `core-js` `URL` implementation is almost full and takes just some kilobytes.

**Comment by lifaon74** [comment]
The core-js url implementation is in the range of 50KB (non gziped) but requires a lot of dependencies to work properly which increases the bundle size. This polyfill (url-polyfill) is arround 13KB (non gziped) and requires no dependencies at all. Moreover, this repo was done before any implementation of URL by core-js.

Of course, now, it may be more interesting to use core-js... It only depends of your needs.

**Comment by zloirock** [comment]
> The core-js url implementation is in the range of 50KB (non gziped)

Minified, without gzip and the rest parts of `core-js`, it takes ~17kb. You are right, my comment was related just to "not possible" and the reasons. But sure, this more simple polyfill make sense for some cases.

**Comment by zloirock** [comment]
More other, your issue was one the reasons for adding `URL` polyfill to `core-js` -)
