### ISSUE TITLE
URLSearchParams and URL referenced globally instead of as properties of 'global' parameter

### ISSUE THREAD

**Issue by andrejpavlovic** [lifaon74/url-polyfill#43]
https://github.com/lifaon74/url-polyfill/blob/d74be6fe18d6790ccc4b64ebd4527b17810186c4/url-polyfill.js#L169-L171

Since we are checking if `URLSearchParams` is present in the `global` variable, we should also then instantiate `URLSearchParams` from the global variable. So instead of `new URLSearchParams` it should be `new global.new URLSearchParams`, since `URLSearchParams` is not necessarily the same as `global.URLSearchParams`.

Fix:
```javascript
 if (!('URLSearchParams' in global) || (new global.URLSearchParams('?a=1').toString() !== 'a=1')) { 
   polyfillURLSearchParams(); 
 } 
```

**Comment by andrejpavlovic** [comment]
This actually seems to be an issue throughout the codebase, where instead of using `global.URLSearchParams` and `global.URL`, the values are being accessed directly at global scope as just `URLSearchParams` and `URL`

https://github.com/lifaon74/url-polyfill/blob/d74be6fe18d6790ccc4b64ebd4527b17810186c4/url-polyfill.js#L173
https://github.com/lifaon74/url-polyfill/blob/d74be6fe18d6790ccc4b64ebd4527b17810186c4/url-polyfill.js#L252
https://github.com/lifaon74/url-polyfill/blob/d74be6fe18d6790ccc4b64ebd4527b17810186c4/url-polyfill.js#L298

**Comment by lifaon74** [comment]
V1.1.5 released, thanks a lot to you.
