### ISSUE TITLE
URLSearchParams with multiple question marks not parsed correctly

### ISSUE THREAD

**Issue by chrischrischris** [lifaon74/url-polyfill#51]
Given the following code:
`new URLSearchParams('?external_url=https://test.com/?plan=team&step=2').toString()`

Results in:
`external_url=https%3A%2F%2Ftest.com%2F%3Fplan&step=2`

Expected:
`external_url=https%3A%2F%2Ftest.com%2F%3Fplan%3Dteam&step=2`

**Comment by lifaon74** [comment]
Actually, this is a really tough one to handle without implementing a proper parser. The polyfill aims to be smaller as possible. If you have any short code proposition don't hesitate to do a pull request.

In you case maybe you could do:
```js
new URLSearchParams(`?external_url=${ encodeURIComponent('https://test.com/?plan=team&step=2') }`).toString()
```
If it may help.

And if you need the full and proper implementation: https://github.com/lifaon74/whatwg-url
