### ISSUE TITLE
URLSearchParams entries not supported on some versions of firefox

### ISSUE THREAD

**Issue by Janpot** [lifaon74/url-polyfill#59]
Looks like older versions of firefox [(v29->v44)](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#Browser_compatibility) don't support `.entries()` and so code like:
```js
new URLSearchParams().entries()
```
is broken for those browsers. Should `url-polyfill` kick in for these?

(see also https://github.com/vercel/next.js/issues/15194)

**Comment by Timer** [comment]
This line should probably be updated to check for entries:
https://github.com/lifaon74/url-polyfill/blob/786963381db78c52e183fa4d99c5e82da163af23/url-polyfill.js#L173

**Comment by lifaon74** [comment]
Feel free to do a pull request, but considering that this represents less than 0.1% of all browser usages: https://caniuse.com/usage-table this is not really an issue.

**Comment by Unsfer** [comment]
Maybe just change
```js
(typeof URLSearchParams.prototype.set === 'function')
```
to
```js
(typeof URLSearchParams.prototype.entries === 'function')
```
?

**Comment by lifaon74** [comment]
V 1.1.10 released
