### ISSUE TITLE
'base' argument is not stringified

### ISSUE THREAD

**Issue by raymondelooff** [lifaon74/url-polyfill#62]
The change from #61 adds a 'toLowerCase' call to the `base` variable. The code assumes that the value passed to the `base` argument is always a string. However, it's also possible to pass an existing `URL` object to both arguments. The values should both be stringified, but only the `url` argument is currently stringified.

Passing an `URL` object to the `base` argument results in the following error:

```
Object doesn't support property or method 'toLowerCase'
```

**Comment by yuriibut** [comment]
+1
