### ISSUE TITLE
Not spec-compliant!

### ISSUE THREAD

**Issue by stevenvachon** [lifaon74/url-polyfill#7]
It's not even an "ES7 specification", it's WHATWG: http://url.spec.whatwg.org

Please avoid false advertising.

**Comment by jhenry9636** [comment]
@stevenvachon You should try and be more helpful considering this is a free tool that you don't have to use. Care to write one yourself?

**Comment by stevenvachon** [comment]
https://npmjs.com/universal-url

**Comment by jhenry9636** [comment]
Damn. I have never been shut up-ed this fast. 

Good for you.
