### ISSUE TITLE
reuse searchParams

### ISSUE THREAD

**Issue by zh99998** [lifaon74/url-polyfill#9]
currently every time get searchParams will create a new object, which is waste memory and cause problem.
currently, in chrome 49.
```javascript
const url = new URL('http://example.com/?a=1');
url.searchParams.set('b','2')
url.searchParams.set('c','3')
console.log(url.toString())
```
=>
```
http://example.com/?%3F%3Fa=1&b=2&c=3
```
will get some mysterious %3F in search string, seems it's caused by duplicated searchParams create.

----
btw, chrome 49 support both `URL` and `URLSearchParams`, but no `url.searchParams`.
this may help you debug.

---
well no i guess wrong.
only one searchParams call will cause this problem too.

```javascript
const url = new URL('http://example.com/?a=1');
const params = url.searchParams;
params.set('b','2');
params.set('c','3');
console.log(url.toString())
```
=>
```
http://example.com/?%3Fa=1&b=2&c=3
```

---

I found that.

this version of chrome native URLSearchParams doesn't cut leading `?`

in chrome 49
```javascript
new URLSearchParams('?a=1').toString() #=> "%3Fa=1"
```

in chrome 60
```javascript
new URLSearchParams('?a=1').toString() #=> "a=1"
```

seems these should be more check before using native URLSearchParams, like
```javascript
  if(!('URLSearchParams' in global && new URLSearchParams('?a=1').toString() === 'a=1')) {
    polyfillURLSearchParams();
  }
```

**Comment by zh99998** [comment]
well no i guess wrong.
only one searchParams call will cause this problem too.

```javascript
const url = new URL('http://example.com/?a=1');
const params = url.searchParams;
params.set('b','2');
params.set('c','3');
console.log(url.toString())
```
=>
```
http://example.com/?%3Fa=1&b=2&c=3
```

**Comment by lifaon74** [comment]
Well, I haven't a chrome 49 version. Could you check what native code exists on URL/URLSearchParams for chrome 49 ? Or even do a pull request if you find a fix ?
This polyfill is intended to be lightweight, so it use the maximum of native functions. Some could be errored. For example, on the last version of chrome (60~62) the URL is not spec compliant because the hash is not url-escaped... But this still covers 99.9% of the usage.

**Comment by lifaon74** [comment]
Could you please provide methe result of `new URLSearchParams('?a=1').toString()' on chrome 49 without polyfill.

I can't accept right now your pull request because of the lacks of test, build and description... I can do it if you tell me what is buggy on chrome 49.

**Comment by zh99998** [comment]
```
new URLSearchParams('?a=1').toString() #=> "%3Fa=1"
```

**Comment by lifaon74** [comment]
Fixed in https://github.com/lifaon74/url-polyfill/commit/53ddfbaccb8ff3e9eeb2cb57f48678cb43c291db ?
